# Generated by Django 4.0.3 on 2022-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='content',
        ),
        migrations.AddField(
            model_name='story',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
