# Generated by Django 4.0.3 on 2022-04-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_story_content_story_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='label',
            field=models.CharField(default='label', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='paragraphs',
            field=models.ManyToManyField(blank=True, related_name='story_paragraphs', to='content.paragraph'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=14)),
                ('chapters', models.ManyToManyField(blank=True, related_name='chapter_stories', to='content.story')),
            ],
        ),
    ]
