# Generated by Django 4.0.3 on 2022-04-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_paragraph_label_alter_story_paragraphs_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapters',
            new_name='stories',
        ),
    ]
