# Generated by Django 4.0.3 on 2022-04-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stories.base')),
                ('title', models.CharField(max_length=14)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
            bases=('stories.base',),
        ),
    ]
