# Generated by Django 4.0.3 on 2022-04-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_chapters_chapter_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
