# Generated by Django 4.0.3 on 2022-04-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_resource_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
