# Generated by Django 4.0.3 on 2022-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
