# Generated by Django 4.0.3 on 2022-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_link_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='group',
            field=models.CharField(choices=[('about', 'about'), ('tech', 'tech')], default='about', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='story_id',
            field=models.IntegerField(default=0),
        ),
    ]
