# Generated by Django 4.0.3 on 2022-04-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_story_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='group',
        ),
        migrations.AddField(
            model_name='story',
            name='page_index',
            field=models.IntegerField(default=1),
        ),
    ]
