# Generated by Django 4.0.3 on 2022-04-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_story_group_story_page_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.base')),
                ('paragraph_id', models.IntegerField(default=0)),
                ('content', models.TextField()),
            ],
            bases=('content.base',),
        ),
        migrations.AddField(
            model_name='story',
            name='paragraphs',
            field=models.ManyToManyField(related_name='story_paragraphs', to='content.paragraph'),
        ),
    ]
