# Generated by Django 4.0.3 on 2022-05-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=14)),
                ('type', models.TextField(choices=[('paragraph', 'paragraph'), ('list', 'list')])),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=14)),
                ('page_index', models.IntegerField(default=1)),
                ('paragraphs', models.ManyToManyField(blank=True, related_name='story_paragraphs', to='blog.paragraph')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('stories', models.ManyToManyField(blank=True, related_name='chapter_stories', to='blog.story')),
            ],
        ),
    ]
