# name: deploy-github
# on: [push]
# jobs:
#   build-vue:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Install Node
#       uses: actions/setup-node@v3
#       with:
#         node-version: '14'

#     - name: Install Packages
#       run: cd client; npm ci

#     - name: Build App
#       run: cd client; npm run build

#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@v4.3.0
#       with:
#         branch: github
#         folder: client/dist
