on:
  push:
    branches:
      - main
    paths:
      -"server/**"
jobs:
  build-django:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add Heroku Remote
      runs: git remote add heroku https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/acmf-dev.git

    - name: Deploy Server to Heroku
      runs: git push heroku `git subtree split --prefix server main`:refs/head/main --force